### PR TITLE
Travis file

### PR DESCRIPTION
**Pull request by bart-de-jonge**
Added .travis.yml

### CODE REVIEW

**Comment by martijnjanssen** [comment]
Could you also setup caching for the dependencies? This allows faster builds. https://docs.travis-ci.com/user/caching/

**Comment by mennoo1996** [comment]
Closing until caching has been set up

**Comment by bart-de-jonge** [comment]
I think travis caching is only for private repositories, can you merge the pull request for now since everything is working fine. Then we can look into the caching thing later on.

**Comment by mennoo1996** [comment]
Sounds reasonable

**Pull request merged**
