### PR TITLE
Google style

### LINKED ISSUE #6: Add failing builds on errors
A build should fail when there are checkstyle errors.

### PR DESCRIPTION
**Pull request by martijnjanssen**
Fixes #6 
The last build should fail due to errors. A fail should be triggered.

### CODE REVIEW

**Comment by bart-de-jonge** [comment]
Please fix the failing build before merging

**Comment by Markvanderuit** [comment]
Looks good, need second member to merge.

**Comment by mennoo1996** [comment]
Great work!

**Comment by Markvanderuit** [comment]
Such merge, wow!

Looks good despite issue.

**Pull request merged**
