### PR TITLE
Pmd findbugs

### PR DESCRIPTION
**Pull request by mennoo1996**
Fix PMD and FindBugs warnings
Wrote tests for added code

### CODE REVIEW

**Comment by bart-de-jonge** [comment]
Looks fine to me, nice work fixing the PMD and findbugs warnings. Are all warnings gone now?

**Comment by mennoo1996** [comment]
I believe one findbugs warning remains. Something about an unwritten variable. When I removed it, things broke. Probably gets confused by Lombok

**Comment by bart-de-jonge** [comment]
Oke we will have to add that in the release

**Comment by martijnjanssen** [comment]
Looks good.

**Pull request merged**
