### PR TITLE
Controller tests

### PR DESCRIPTION
**Pull request by bart-de-jonge**
Added tests for the detailViewController. That class has 100% test coverage now.

### CODE REVIEW

**Comment by mennoo1996** [comment]
It seems something is going wrong with your tests. Please look into that. Other than that, good work testing our application!

**Comment by bart-de-jonge** [comment]
@mennoo1996 Travis didn't like gui testing, fixed that now by added xvfb

**Comment by geenen124** [comment]
Looking forward to using the ApplicationTest for further testing!

**Comment by Markvanderuit** [comment]
Looks fine. Tests pass.

And nice find with the GUI testing.

**Pull request merged**
