### PR TITLE
Checkstyle configuration

### PR DESCRIPTION
**Pull request by mennoo1996**
I added and configured some checkstyle rules. Please check if you have any comments or problems.
Let's wait with merging this branch before everyone has approved the current ruleset, so that we can keep this ruleset from this point onwards.

### CODE REVIEW

**Comment by bart-de-jonge** [comment]
To me these rules look fine, if we encounter some real problems in the future we can always see if we can change them.

**Comment by mennoo1996** [comment]
New commit adding a suppression filter to avoid checkstyle in test classes

**Comment by Markvanderuit** [comment]
Looks good. Second member can confirm and merge!

**Comment by martijnjanssen** [comment]
Wow, it is fixed. I am very satisfied to see this issue fixed! Thanks!

**Pull request merged**
